// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClHZphDOcPXUSTgfoHhhYfPaoJeaw4VrI',
    appId: '1:523643609521:web:6e56be4785d11782711d90',
    messagingSenderId: '523643609521',
    projectId: 'firstfirebaseiosapp',
    authDomain: 'firstfirebaseiosapp.firebaseapp.com',
    storageBucket: 'firstfirebaseiosapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRoM7Wj7WxckETNyPcUm6vD45QJcQ3blA',
    appId: '1:523643609521:android:23a04bd9f33e512e711d90',
    messagingSenderId: '523643609521',
    projectId: 'firstfirebaseiosapp',
    storageBucket: 'firstfirebaseiosapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvx5cp1w9B0aQl39L0nZ6r2xSlhdcAuyk',
    appId: '1:523643609521:ios:895e9b156a4b9c87711d90',
    messagingSenderId: '523643609521',
    projectId: 'firstfirebaseiosapp',
    storageBucket: 'firstfirebaseiosapp.appspot.com',
    iosBundleId: 'com.example.firebaseSampleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvx5cp1w9B0aQl39L0nZ6r2xSlhdcAuyk',
    appId: '1:523643609521:ios:882a9fd0f92a569c711d90',
    messagingSenderId: '523643609521',
    projectId: 'firstfirebaseiosapp',
    storageBucket: 'firstfirebaseiosapp.appspot.com',
    iosBundleId: 'com.example.firebaseSampleApp.RunnerTests',
  );
}
